image: node:22

definitions:
  steps:
    - step: &validations
        name: Validations
        caches:
          - node
        script:
          - yarn install --frozen-lockfile
          - yarn lint
          - yarn tsc

    - step: &build
        name: Build
        depends_on:
          - Validations
        caches:
          - node
        script:
          - yarn install --frozen-lockfile
          - cp .env.development .env
          - yarn build

pipelines:
  default:
    - step: *validations
    - step: *build

  # branches:
  #   main:
  #     - step: *validations
  #     - step: *build

  # pull-requests:
  #   "**":
  #     - step: *validations
  #     - step: *build
