image: node:22

definitions:
  steps:
    # Build - Dev
    - step: &build-dev
        name: Build - Dev
        caches:
          - node
        artifacts:
          - dist/**
        script:
          - yarn install --frozen-lockfile
          - yarn build:dev

    # Build - Prod
    - step: &build-prod
        name: Build - Prod
        caches:
          - node
        artifacts:
          - dist/**
        script:
          - yarn install --frozen-lockfile
          - yarn build:prod

    # Deploy - Dev
    - step: &deploy-dev
        name: Deploy - Dev
        trigger: manual
        depends_on:
          - Build - Dev
        caches:
          - node
        artifacts:
          download: true
          paths:
            - dist/**
        script:
          - echo "Add development deployment steps"

    # Deploy - Prod
    - step: &deploy-prod
        name: Deploy - Prod
        trigger: manual
        depends_on:
          - Build - Prod
        caches:
          - node
        artifacts:
          download: true
          paths:
            - dist/**
        script:
          - echo "Add production deployment steps"

pipelines:
  pull-requests:
    main:
      - step: *build-dev

  branches:
    main:
      - step: *build-dev
      - step: *deploy-dev

  custom:
    release:
      - step: *build-prod
      - step: *deploy-prod
