name: Production

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  validations:
    name: Validations
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Install Dependencies
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      # Run Lint
      - name: Run Lint
        run: yarn run lint

      # Run Type Check
      - name: Run Type Check
        run: yarn run tsc

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [validations]
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Install Dependencies
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      # Run Build
      - name: Run Build - Production
        run: yarn build:prod

      # Upload Build Artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Download Build Artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist

      # Deploy
      - name: Deploy
        run: |
          # Add your deployment commands here
          # For example, you can use rsync, scp, or any other deployment tool
          # rsync -avz dist/ user@server:/path/to/deploy/
          echo "Deployment complete!"
